components:
    schemas:
        ApiResponse:
            properties:
                code:
                    format: int32
                    type: integer
                data:
                    type: object
                message:
                    type: string
            type: object
info:
    title: gin-demo
    version: 1.0.0
openapi: 3.0.3
paths:
    /api/v1/users:
        get:
            operationId: listUsers
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ApiResponse'
                    description: HTTP 200 response
                "400":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ApiResponse'
                    description: HTTP 400 response
                default:
                    description: ""
            summary: listUsers
        post:
            operationId: createUser
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
            responses:
                "201":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ApiResponse'
                    description: HTTP 201 response
                "400":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ApiResponse'
                    description: HTTP 400 response
                default:
                    description: ""
            summary: createUser
    /api/v1/users/{id}:
        get:
            operationId: getUserByID
            parameters:
                - description: Path parameter
                  in: path
                  name: id
                  required: true
                  schema:
                    type: string
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ApiResponse'
                    description: HTTP 200 response
                "400":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ApiResponse'
                    description: HTTP 400 response
                "404":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ApiResponse'
                    description: HTTP 404 response
                default:
                    description: ""
            summary: getUserByID
    /api/v1/users/{id}/profile:
        post:
            operationId: updateProfile
            parameters:
                - description: Path parameter
                  in: path
                  name: id
                  required: true
                  schema:
                    type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ApiResponse'
                    description: HTTP 200 response
                "400":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ApiResponse'
                    description: HTTP 400 response
                "404":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ApiResponse'
                    description: HTTP 404 response
                default:
                    description: ""
            summary: updateProfile
    /api/v1/users/upload:
        post:
            operationId: uploadFile
            parameters:
                - description: Query parameter
                  in: query
                  name: file
                  required: true
                  schema:
                    type: string
                - description: Query parameter
                  in: query
                  name: userId
                  required: true
                  schema:
                    type: string
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ApiResponse'
                    description: HTTP 200 response
                "400":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ApiResponse'
                    description: HTTP 400 response
                default:
                    description: ""
            summary: uploadFile
