// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CreateUserRequest struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	FullName string `json:"fullName"`
	Age      int    `json:"age"`
}

type FileUploadResponse struct {
	Code    int              `json:"code"`
	Message string           `json:"message"`
	Data    FileUploadResult `json:"data"`
}

type FileUploadResult struct {
	Filename    string `json:"filename"`
	Size        int64  `json:"size"`
	ContentType string `json:"contentType"`
	Message     string `json:"message"`
}

type ListUsersRequest struct {
	Page     int    `form:"page,default=0"`
	Size     int    `form:"size,default=10"`
	Username string `form:"username,optional"`
}

type UpdateProfileRequest struct {
	FullName string `form:"fullName,optional"`
	Email    string `form:"email,optional"`
	Age      int    `form:"age,optional"`
}

type User struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
	FullName string `json:"fullName"`
	Age      int    `json:"age"`
}

type UserList struct {
	Content    []User `json:"content"`
	PageNumber int    `json:"pageNumber"`
	PageSize   int    `json:"pageSize"`
	Total      int64  `json:"total"`
	TotalPages int    `json:"totalPages"`
}

type UserListResponse struct {
	Code    int      `json:"code"`
	Message string   `json:"message"`
	Data    UserList `json:"data"`
}

type UserResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Data    *User  `json:"data"`
}
